gadgets: seccomp: Include seccompprofile from v1beta1.
seccompprofile was graduated from v1alpha1 to v1beta1 in 6e12fe5f2daa
("Graduate seccomp profile from v1alpha1 to v1beta1") on
kubernetes-sigs/security-profiles-operator.

Since some packages were updated, this commit also does the following:
1. it bumps k8s.io/cli-runtime from v0.20.6 to v0.21.0 which in turn
bumps sigs.k8s.io/kustomize to avoid this compilation error:
/go/pkg/mod/sigs.k8s.io/kustomize@v2.0.3+incompatible/pkg/transformers/config/factorycrd.go:71:47: cannot use api.Schema.SchemaProps.Properties (type map[string]"k8s.io/kube-openapi/pkg/validation/spec".Schema) as type myProperties in argument to looksLikeAk8sType
2. It fixes API change in syscalls.go.
3. It import gomega/types with an alias and use this alias to refer to
GomegaMatcher.

Signed-off-by: Francis Laniel <flaniel@linux.microsoft.com>